/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegulationsRouteImport } from './routes/regulations'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FindPathRouteImport } from './routes/find-path'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntityIdRouteImport } from './routes/entity/$id'
import { Route as BillIdRouteImport } from './routes/bill/$id'
import { Route as AidCountryCodeRouteImport } from './routes/aid/country/$code'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulationsRoute = RegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FindPathRoute = FindPathRouteImport.update({
  id: '/find-path',
  path: '/find-path',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillIdRoute = BillIdRouteImport.update({
  id: '/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AidCountryCodeRoute = AidCountryCodeRouteImport.update({
  id: '/aid/country/$code',
  path: '/aid/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/find-path': typeof FindPathRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/regulations': typeof RegulationsRoute
  '/search': typeof SearchRoute
  '/bill/$id': typeof BillIdRoute
  '/entity/$id': typeof EntityIdRoute
  '/aid/country/$code': typeof AidCountryCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/find-path': typeof FindPathRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/regulations': typeof RegulationsRoute
  '/search': typeof SearchRoute
  '/bill/$id': typeof BillIdRoute
  '/entity/$id': typeof EntityIdRoute
  '/aid/country/$code': typeof AidCountryCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/find-path': typeof FindPathRoute
  '/how-it-works': typeof HowItWorksRoute
  '/news': typeof NewsRoute
  '/patterns': typeof PatternsRoute
  '/privacy': typeof PrivacyRoute
  '/regulations': typeof RegulationsRoute
  '/search': typeof SearchRoute
  '/bill/$id': typeof BillIdRoute
  '/entity/$id': typeof EntityIdRoute
  '/aid/country/$code': typeof AidCountryCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/find-path'
    | '/how-it-works'
    | '/news'
    | '/patterns'
    | '/privacy'
    | '/regulations'
    | '/search'
    | '/bill/$id'
    | '/entity/$id'
    | '/aid/country/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/find-path'
    | '/how-it-works'
    | '/news'
    | '/patterns'
    | '/privacy'
    | '/regulations'
    | '/search'
    | '/bill/$id'
    | '/entity/$id'
    | '/aid/country/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/find-path'
    | '/how-it-works'
    | '/news'
    | '/patterns'
    | '/privacy'
    | '/regulations'
    | '/search'
    | '/bill/$id'
    | '/entity/$id'
    | '/aid/country/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  FindPathRoute: typeof FindPathRoute
  HowItWorksRoute: typeof HowItWorksRoute
  NewsRoute: typeof NewsRoute
  PatternsRoute: typeof PatternsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegulationsRoute: typeof RegulationsRoute
  SearchRoute: typeof SearchRoute
  BillIdRoute: typeof BillIdRoute
  EntityIdRoute: typeof EntityIdRoute
  AidCountryCodeRoute: typeof AidCountryCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulations': {
      id: '/regulations'
      path: '/regulations'
      fullPath: '/regulations'
      preLoaderRoute: typeof RegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-path': {
      id: '/find-path'
      path: '/find-path'
      fullPath: '/find-path'
      preLoaderRoute: typeof FindPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/$id': {
      id: '/bill/$id'
      path: '/bill/$id'
      fullPath: '/bill/$id'
      preLoaderRoute: typeof BillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid/country/$code': {
      id: '/aid/country/$code'
      path: '/aid/country/$code'
      fullPath: '/aid/country/$code'
      preLoaderRoute: typeof AidCountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  FindPathRoute: FindPathRoute,
  HowItWorksRoute: HowItWorksRoute,
  NewsRoute: NewsRoute,
  PatternsRoute: PatternsRoute,
  PrivacyRoute: PrivacyRoute,
  RegulationsRoute: RegulationsRoute,
  SearchRoute: SearchRoute,
  BillIdRoute: BillIdRoute,
  EntityIdRoute: EntityIdRoute,
  AidCountryCodeRoute: AidCountryCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
