// ISO 3166-1 alpha-2 to human-readable country name
// Focused on top Canadian international aid recipient countries
export const COUNTRY_NAMES: Record<string, string> = {
  AF: 'Afghanistan',
  AL: 'Albania',
  DZ: 'Algeria',
  AO: 'Angola',
  AR: 'Argentina',
  AM: 'Armenia',
  BD: 'Bangladesh',
  BJ: 'Benin',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CF: 'Central African Republic',
  TD: 'Chad',
  CO: 'Colombia',
  CD: 'Congo (DRC)',
  CG: 'Congo (Republic)',
  CI: "Côte d'Ivoire",
  CU: 'Cuba',
  EG: 'Egypt',
  SV: 'El Salvador',
  ER: 'Eritrea',
  ET: 'Ethiopia',
  GE: 'Georgia',
  GH: 'Ghana',
  GT: 'Guatemala',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  HT: 'Haiti',
  HN: 'Honduras',
  ID: 'Indonesia',
  IQ: 'Iraq',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  LB: 'Lebanon',
  LR: 'Liberia',
  LY: 'Libya',
  MG: 'Madagascar',
  MW: 'Malawi',
  ML: 'Mali',
  MR: 'Mauritania',
  MX: 'Mexico',
  MD: 'Moldova',
  MN: 'Mongolia',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NP: 'Nepal',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  PK: 'Pakistan',
  PS: 'Palestinian Territories',
  PE: 'Peru',
  PH: 'Philippines',
  RW: 'Rwanda',
  SN: 'Senegal',
  SL: 'Sierra Leone',
  SO: 'Somalia',
  ZA: 'South Africa',
  SS: 'South Sudan',
  SD: 'Sudan',
  SR: 'Suriname',
  SY: 'Syria',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  UG: 'Uganda',
  UA: 'Ukraine',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
} as const

/**
 * Returns a human-readable country name for an ISO 3166-1 alpha-2 code.
 * Falls back to the raw code string if unmapped.
 */
export const getCountryName = (code: string): string =>
  COUNTRY_NAMES[code.toUpperCase()] ?? code

/**
 * Converts a 2-letter ISO country code to a Unicode flag emoji using regional indicator symbols.
 * Example: "CA" -> "🇨🇦"
 */
export const getFlag = (code: string): string => {
  const upper = code.toUpperCase()
  if (upper.length !== 2) return ''
  const base = 0x1f1e6 - 65 // 'A'.charCodeAt(0) = 65
  return String.fromCodePoint(base + upper.charCodeAt(0), base + upper.charCodeAt(1))
}

// OECD DAC sector codes (5-digit) — grouped by 3-digit prefix themes
// Reference: https://www.oecd.org/dac/stats/dacandcrscodelists.htm
export const DAC_SECTORS: Record<string, string> = {
  // Education
  '11110': 'Education Policy & Admin',
  '11120': 'Education Facilities & Training',
  '11130': 'Teacher Training',
  '11182': 'Educational Research',
  '11220': 'Primary Education',
  '11230': 'Basic Life Skills for Youth',
  '11240': 'Early Childhood Education',
  '11320': 'Secondary Education',
  '11330': 'Vocational Training',
  '11420': 'Higher Education',
  '11430': 'Advanced Technical Education',
  // Health
  '12110': 'Health Policy & Admin',
  '12191': 'Medical Services',
  '12196': 'Health Personnel Development',
  '12220': 'Basic Health Care',
  '12230': 'Basic Health Infrastructure',
  '12240': 'Basic Nutrition',
  '12250': 'Infectious Disease Control',
  '12261': 'Health Education',
  '12262': 'Malaria Control',
  '12263': 'Tuberculosis Control',
  '12281': 'Health Personnel Education',
  // Water & Sanitation
  '14010': 'Water Sector Policy & Admin',
  '14015': 'Water Resources Conservation',
  '14020': 'Water Supply & Sanitation',
  '14021': 'Water Supply',
  '14022': 'Sanitation',
  '14030': 'Basic Drinking Water Supply',
  '14031': 'Basic Sanitation',
  '14032': 'Waste Management',
  '14040': 'River Development',
  '14050': 'Waste Management',
  '14081': 'Water Supply & Sanitation Research',
  // Government & Civil Society
  '15110': 'Public Sector Policy & Admin',
  '15111': 'Public Finance Management',
  '15112': 'Decentralisation',
  '15113': 'Anti-Corruption',
  '15114': 'Domestic Revenue Mobilisation',
  '15130': 'Legal & Judicial Development',
  '15150': 'Democratic Participation',
  '15151': 'Elections',
  '15152': 'Legislatures & Political Parties',
  '15153': 'Media & Free Flow of Information',
  '15160': 'Human Rights',
  '15170': 'Women\'s Equality & Empowerment',
  '15180': 'Ending Violence Against Women',
  '15185': 'Local Government',
  '15190': 'Facilitation of Orderly, Safe Migration',
  '15210': 'Security System Management',
  '15220': 'Civilian Peace-Building',
  '15230': 'Participation in International Peacekeeping',
  '15240': 'Reintegration & SALW Control',
  '15250': 'Removal of Land Mines',
  '15261': 'Child Soldiers',
  // Social Infrastructure
  '16010': 'Social Protection',
  '16020': 'Employment Policy & Admin',
  '16050': 'Multisector Aid for Basic Social Services',
  '16062': 'Statistical Capacity Building',
  '16063': 'Narcotics Control',
  '16064': 'Social Mitigation of HIV/AIDS',
  '16065': 'Research/Scientific Institutions',
  '16066': 'Culture & Recreation',
  '16070': 'Labour Rights',
  '16080': 'Ending Child Labour',
  // Economic Infrastructure
  '21010': 'Transport Policy & Admin',
  '21020': 'Road Transport',
  '21030': 'Rail Transport',
  '21040': 'Water Transport',
  '21050': 'Air Transport',
  '21061': 'Storage',
  '21081': 'Education & Training in Transport',
  '22010': 'Communications Policy & Admin',
  '22020': 'Telecommunications',
  '22030': 'Radio/TV/Print Media',
  '23010': 'Energy Policy & Admin',
  '23020': 'Power Generation/Renewable Sources',
  '23030': 'Power Generation/Non-Renewable Sources',
  '23040': 'Electrical Transmission/Distribution',
  '23050': 'Gas Distribution',
  '23061': 'Oil & Gas',
  '23062': 'Oil & Gas',
  '23063': 'Coal',
  '23064': 'Nuclear Power Plants',
  '23065': 'Biofuel',
  '23066': 'Energy Conservation & Demand',
  '23067': 'Hydro-Electric Power',
  '23068': 'Solar Energy',
  '23069': 'Wind Power',
  '23070': 'Geothermal Energy',
  '23071': 'Ocean Power',
  // Agriculture
  '31110': 'Agricultural Policy & Admin',
  '31120': 'Agricultural Development',
  '31130': 'Agricultural Land Resources',
  '31140': 'Agricultural Water Resources',
  '31150': 'Agricultural Inputs',
  '31161': 'Food Crop Production',
  '31162': 'Industrial Crops',
  '31163': 'Livestock',
  '31164': 'Agrarian Reform',
  '31165': 'Agricultural Alternative Development',
  '31166': 'Agricultural Extension',
  '31182': 'Agricultural Research',
  '31191': 'Agricultural Services',
  '31192': 'Plant & Post-Harvest Protection',
  '31193': 'Agricultural Financial Services',
  '31194': 'Agricultural Cooperatives',
  '31195': 'Livestock/Veterinary Services',
  '31210': 'Forestry Policy & Admin',
  '31220': 'Forestry Development',
  '31261': 'Fuelwood/Charcoal',
  '31281': 'Forestry Research',
  '31291': 'Forestry Services',
  '31310': 'Fishing Policy & Admin',
  '31320': 'Fishery Development',
  '31381': 'Fishery Research',
  '31391': 'Fishery Services',
  // Industry & Business
  '32110': 'Industrial Policy & Admin',
  '32120': 'Industrial Development',
  '32130': 'Small & Medium Enterprises (SME)',
  '32140': 'Cottage Industries & Handicrafts',
  '32161': 'Agro-Industries',
  '32162': 'Forest Industries',
  '32163': 'Textiles, Leather & Substitutes',
  '32164': 'Chemicals',
  '32165': 'Fertiliser Plants',
  '32166': 'Cement/Lime/Plaster',
  '32167': 'Energy Manufacturing',
  '32168': 'Pharmaceutical Production',
  '32169': 'Basic Metal Industries',
  '32170': 'Non-Ferrous Metal Industries',
  '32171': 'Engineering',
  '32172': 'Transport Equipment Industry',
  '32182': 'Technological Research & Development',
  '32210': 'Mineral Resources Policy & Admin',
  '32220': 'Mineral Prospection & Exploration',
  '32261': 'Coal',
  '32262': 'Oil & Gas',
  '32263': 'Ferrous Metal Mining',
  '32264': 'Nonferrous Metal Mining',
  '32265': 'Precious Metal Mining',
  '32266': 'Industrial Minerals',
  '32267': 'Fertiliser Minerals',
  '32268': 'Offshore Mining',
  // Environment
  '41010': 'Environmental Policy & Admin',
  '41020': 'Biosphere Protection',
  '41030': 'Bio-Diversity',
  '41040': 'Site Preservation',
  '41050': 'Flood Prevention',
  '41081': 'Environmental Research',
  '41082': 'Environmental Education & Training',
  // Multi-Sector
  '43010': 'Multi-Sector Aid',
  '43030': 'Urban Development & Management',
  '43031': 'Urban Land Policy',
  '43040': 'Rural Development',
  '43041': 'Rural Land Policy',
  '43050': 'Non-Agricultural Alternative Development',
  '43060': 'Disaster Risk Reduction',
  '43071': 'Food Security Policy',
  '43072': 'Household Food Security',
  '43073': 'Food Safety',
  '43081': 'Multi-Sector Education/Training',
  '43082': 'Research/Scientific Institutions',
  // Budget Support
  '51010': 'General Budget Support',
  '51020': 'Sector Budget Support',
  // Food Aid
  '52010': 'Food Aid/Food Security',
  // Other Commodity Assistance
  '53010': 'Non-Food Commodity Assistance',
  // Humanitarian Aid
  '60010': 'Humanitarian Aid',
  '60020': 'Emergency Response',
  '60030': 'Reconstruction Relief',
  '60040': 'Disaster Prevention',
  '72010': 'Material Relief & Services',
  '72040': 'Emergency Food Aid',
  '72050': 'Relief Coordination',
  '73010': 'Immediate Post-Emergency Reconstruction',
  '74010': 'Disaster Prevention & Preparedness',
  // Admin / Other
  '91010': 'Admin Costs (Donors)',
  '92010': 'Support to NGOs',
  '92020': 'Support to UN Agencies',
  '92030': 'Support to World Bank',
  '92040': 'Support to IMF',
  '92050': 'Support to Regional Dev Banks',
  '93010': 'Refugees in Donor Countries',
  '99810': 'Unallocated/Unspecified',
  '99820': 'Promotion of Development Awareness',
} as const

// Theme groupings by 3-digit DAC sector prefix
const SECTOR_PREFIX_THEMES: Record<string, string> = {
  '111': 'Education',
  '112': 'Education',
  '113': 'Education',
  '114': 'Education',
  '121': 'Health',
  '122': 'Health',
  '123': 'Population & Reproductive Health',
  '124': 'Water Supply & Sanitation',
  '130': 'Government & Civil Society',
  '140': 'Water & Sanitation',
  '151': 'Government & Civil Society',
  '152': 'Conflict, Peace & Security',
  '160': 'Social Protection',
  '210': 'Transport',
  '220': 'Communications',
  '230': 'Energy',
  '311': 'Agriculture',
  '312': 'Forestry',
  '313': 'Fishing',
  '321': 'Industry',
  '322': 'Mining',
  '331': 'Trade',
  '332': 'Tourism',
  '410': 'Environment',
  '430': 'Multi-Sector',
  '510': 'Budget Support',
  '520': 'Food Aid',
  '530': 'Commodity Assistance',
  '600': 'Humanitarian Aid',
  '720': 'Humanitarian Aid',
  '730': 'Reconstruction',
  '740': 'Disaster Prevention',
  '910': 'Admin & Other',
  '920': 'Civil Society Support',
  '930': 'Refugees',
  '998': 'Unallocated',
}

/**
 * Maps a 5-digit DAC sector code to a broad thematic label.
 * First tries exact lookup, then falls back to 3-digit prefix grouping.
 * Returns the raw code as a last resort.
 */
export const getSectorTheme = (code: string): string => {
  if (!code) return 'Unknown'
  const exact = DAC_SECTORS[code]
  if (exact) return exact
  const prefix = code.slice(0, 3)
  const theme = SECTOR_PREFIX_THEMES[prefix]
  if (theme) return theme
  return code
}
